on:
    push:
        branches:
            - master

jobs: 
    generate-index:
        name: Generate index.md
        runs-on: ubuntu-latest
        steps:
            -   name: Create 
                run: |
                    with `**\README.md` as f:
                        file = f.read()
                shell: python


    

